services:
  frontend:
    image: evgenyarbatov/gpx-frontend:latest
    container_name: "gpx-frontend"
    environment:
      - SERVER_PORT=8080
      - GRPC_SERVER=backend:9090
    ports:
      - 8080:8080
    networks:
      - default
    restart: unless-stopped
  backend:
    image: evgenyarbatov/gpx-backend:latest
    container_name: "gpx-backend"
    environment:
      - SERVER_PORT=9090
      - DB_HOST=postgis
    ports:
      - 9090:9090
    networks:
      - default
    restart: unless-stopped
  postgis:
    image: evgenyarbatov/gpx-postgis:latest
    container_name: "gpx-postgis"
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge