services:
  postgis:
    image: evgenyarbatov/gpx-postgis:latest
    container_name: "gpx-postgis"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "gpx"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped
  backend:
    image: evgenyarbatov/gpx-backend:latest
    container_name: "gpx-backend"
    environment:
      - SERVER_PORT=9090
      - DB_HOST=postgis
    ports:
      - 9090:9090
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9090"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgis:
        condition: service_healthy
  frontend:
    image: evgenyarbatov/gpx-frontend:latest
    container_name: "gpx-frontend"
    environment:
      - SERVER_PORT=8080
      - GRPC_SERVER=backend:9090
    ports:
      - 8080:8080
    networks:
      - default
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy





networks:
  default:
    driver: bridge