# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpxtracker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10gpxtracker.proto\"+\n\x0fLocationRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\"\"\n\x0f\x41\x64\x64ressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"$\n\x10\x44istanceResponse\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\"!\n\x0cTimeResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x16\n\x07GPXFile\x12\x0b\n\x03xml\x18\x01 \x01(\t2\x9e\x02\n\nGPXTracker\x12\x32\n\nGetAddress\x12\x10.LocationRequest\x1a\x10.AddressResponse\"\x00\x12=\n\x14GetRemainginDistance\x12\x10.LocationRequest\x1a\x11.DistanceResponse\"\x00\x12;\n\x12GetCoveredDistance\x12\x10.LocationRequest\x1a\x11.DistanceResponse\"\x00\x12\x34\n\x0fGetTimeEstimate\x12\x10.LocationRequest\x1a\r.TimeResponse\"\x00\x12*\n\nGetGPXFile\x12\x10.LocationRequest\x1a\x08.GPXFile\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpxtracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONREQUEST']._serialized_start=20
  _globals['_LOCATIONREQUEST']._serialized_end=63
  _globals['_ADDRESSRESPONSE']._serialized_start=65
  _globals['_ADDRESSRESPONSE']._serialized_end=99
  _globals['_DISTANCERESPONSE']._serialized_start=101
  _globals['_DISTANCERESPONSE']._serialized_end=137
  _globals['_TIMERESPONSE']._serialized_start=139
  _globals['_TIMERESPONSE']._serialized_end=172
  _globals['_GPXFILE']._serialized_start=174
  _globals['_GPXFILE']._serialized_end=196
  _globals['_GPXTRACKER']._serialized_start=199
  _globals['_GPXTRACKER']._serialized_end=485
# @@protoc_insertion_point(module_scope)
